In [1]:
import sys
import warnings
import panel as pn

# DO NOT remove this line below, otherwise the app won't be found
sys.path.append('..')
warnings.filterwarnings('ignore')

In [2]:
import sim2bids
from sim2bids.sim2bids import MainArea

pn.extension('tabulator', 'ace', 'jsoneditor', 'ipywidgets', sizing_mode='stretch_width', notifications=True)

NotificationArea(sizing_mode='stretch_width')

In [3]:
path = '../output'
sys.path.append(path)

sim2bids.app.app.SoftwareVersion = 2.6
sim2bids.app.app.SoftwareRepository = 'https://github.com/the-virtual-brain/tvb-root/releases/tag/2.6'
sim2bids.app.app.SoftwareName = 'TVB'

app = MainArea()
pn.serve(app.view())

INFO:bokeh.server.server:Starting Bokeh server version 2.4.2 (running on Tornado 6.1)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)


Launching server at http://localhost:58838


INFO:tornado.access:200 GET / (127.0.0.1) 438.65ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/jsoneditor/npm/jsoneditor@9.1.9/dist/jsoneditor.min.css (127.0.0.1) 214.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/datatabulator/tabulator-tables@4.9.3/dist/css/tabulator_simple.min.css (127.0.0.1) 8.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/notificationarea/npm/notyf@3/notyf.min.css (127.0.0.1) 11.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/notificationarea/ajax/libs/font-awesome/5.15.1/css/all.min.css (127.0.0.1) 16.00ms
INFO:tornado.access:200 GET /static/extensions/panel/css/alerts.css (127.0.0.1) 20.00ms
INFO:tornado.access:200 GET /static/extensions/panel/css/card.css (127.0.0.1) 38.00ms
INFO:tornado.access:200 GET /static/extensions/panel/css/debugger.css (127.0.0.1) 10.99ms
INFO:tornado.access:200 GET /static/extensions/panel/css/json.css (127.0.0.1) 17.00ms
INFO:tornado.access:200 GET /static/extens

In [5]:
import scipy.io as sio

sio.loadmat('C:/Users/dinar/Desktop/gsoc_data/New_Connectomes_MRTrix3/AA_20120815_SC.mat')

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Fri Aug 12 11:17:57 2016',
 '__version__': '1.0',
 '__globals__': [],
 'ids': array([[(array(['L.BSTS  ctx-lh-bankssts'], dtype='<U23'),),
         (array(['L.CACG  ctx-lh-caudalanteriorcingulate  '], dtype='<U40'),),
         (array(['L.CMFG  ctx-lh-caudalmiddlefrontal      '], dtype='<U40'),),
         (array(['L.CU    ctx-lh-cuneus                   '], dtype='<U40'),),
         (array(['L.EC    ctx-lh-entorhinal               '], dtype='<U40'),),
         (array(['L.FG    ctx-lh-fusiform                 '], dtype='<U40'),),
         (array(['L.IPG   ctx-lh-inferiorparietal         '], dtype='<U40'),),
         (array(['L.ITG   ctx-lh-inferiortemporal         '], dtype='<U40'),),
         (array(['L.ICG   ctx-lh-isthmuscingulate         '], dtype='<U40'),),
         (array(['L.LOG   ctx-lh-lateraloccipital         '], dtype='<U40'),),
         (array(['L.LOFG  ctx-lh-lateralorbitofrontal     '], dtype='<U40'),),
   

In [9]:
import pandas as pd 

pd.read_csv('C:/Users/dinar/Desktop/gsoc_data/New_Connectomes_MRTrix3/AA_20120815_aparc_to_DWI_mrtrixlabels.csv', header=None, index_col=None, sep='\s')



0      1       2       3      4      5      6      7     8      9   \
0   46284      1      32      14      0   1205  70421  27298  5054   1155   
1       0  81121    8002       0      0      1     11      1  3694      2   
2       0      0  260815       1      0     18    468     71   228     26   
3       0      0       0  129727      0    598   1591    875    30  70389   
4       0      0       0       0  29245  14305      0   1496     0      0   
..    ...    ...     ...     ...    ...    ...    ...    ...   ...    ...   
79      0      0       0       0      0      0      0      0     0      0   
80      0      0       0       0      0      0      0      0     0      0   
81      0      0       0       0      0      0      0      0     0      0   
82      0      0       0       0      0      0      0      0     0      0   
83      0      0       0       0      0      0      0      0     0      0   

    ...    74    75   76  77   78     79     80     81      82       83  
0   ...     0     1    4   0   11      0      0      0       2        0  
1   ...  1336  3957  111   2  154      0      0      1    1964        0  
2   ...   115   607   46   1  118      0      0      0     412        0  
3   ...     0     0  177   0    0      0      0      0       0        0  
4   ...     0     0    0   0    0      0      0      0       0       11  
..  ...   ...   ...  ...  ..  ...    ...    ...    ...     ...      ...  
79  ...     0     0    0   0    0  11390      0      0      23        0  
80  ...     0     0    0   0    0      0  35531      0    4964        0  
81  ...     0     0    0   0    0      0      0  27041    2154        7  
82  ...     0     0    0   0    0      0      0      0  247164       60  
83  ...     0     0    0   0    0      0      0      0       0  1384351  

[84 rows x 84 columns]

In [10]:
sio.loadmat('C:/Users/dinar/Desktop/gsoc_data/Micha-TVB-paper/AA_20120815_SC.mat')

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Tue Apr  8 07:01:42 2014',
 '__version__': '1.0',
 '__globals__': [],
 'steps2lenght': array(['The steplength used for this tracking was 0.2mm/step. So for instance, a track length of 10 steps means 2mm.'],
       dtype='<U108'),
 'SC_cap_agg_counts': array([[    0,     1,  1526, ...,     0,     4,     2],
        [    1,     0,    58, ...,     0,     0,    24],
        [ 1526,    58,     0, ...,     0,     0,    54],
        ...,
        [    0,     0,     0, ...,     0,     0, 67012],
        [    4,     0,     0, ...,     0,     0,  5641],
        [    2,    24,    54, ..., 67012,  5641,     0]]),
 'SC_cap_agg_bwflav1': array([[   0,    1, 1415, ...,    0,    4,    2],
        [   1,    0,   57, ...,    0,    0,   23],
        [1415,   57,    0, ...,    0,    0,   54],
        ...,
        [   0,    0,    0, ...,    0,    0, 6724],
        [   4,    0,    0, ...,    0,    0, 1797],
        [   2,   23,   54, ..., 67

In [11]:
sio.loadmat('C:/Users/dinar/Desktop/gsoc_data/Micha-TVB-paper/AA_20120815_fMRI_new.mat')

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Sun Mar 23 18:25:10 2014',
 '__version__': '1.0',
 '__globals__': [],
 'ROI_ID_table': array([[ 1.00000000e+00,  0.00000000e+00,  9.82160000e+04, ...,
         -1.25138600e+03,  1.93981875e+04,  2.06495742e+04],
        [ 2.00000000e+00,  2.00000000e+00,  6.32500000e+03, ...,
          4.62146000e+01,  1.60500693e+04,  1.60038545e+04],
        [ 3.00000000e+00,  4.00000000e+00,  2.03000000e+02, ...,
          7.57800390e+03,  1.74871406e+04,  9.90913670e+03],
        ...,
        [ 1.08000000e+02,  2.03300000e+03,  5.70000000e+01, ...,
          0.00000000e+00,  5.41270800e+03,  5.41270800e+03],
        [ 1.09000000e+02,  2.03400000e+03,  2.80000000e+01, ...,
          1.07815723e+04,  1.42260195e+04,  3.44444730e+03],
        [ 1.10000000e+02,  2.03500000e+03,  2.15000000e+02, ...,
          6.78981700e+02,  1.51475752e+04,  1.44685938e+04]]),
 'FC_cc': array([[ 1.        ,  0.54857184, -0.10775857, ...,  0.07022364,


In [24]:
sio.loadmat('C:/Users/dinar/Desktop/gsoc_data/Micha-TVB-paper/AC_20151014_1500_SC.mat').keys()

dict_keys(['__header__', '__version__', '__globals__', 'SC_dist_median_agg_new', 'SC_dist_mean_agg_new', 'SC_cap_agg_counts', 'SC_cap_agg_bwflav1', 'SC_cap_agg_bwflav2', 'SC_cap_agg_counts_norm', 'SC_cap_agg_bwflav1_norm', 'SC_cap_agg_bwflav2_norm', 'SC_cap_agg_counts_norm_log', 'SC_cap_agg_bwflav1_norm_log', 'SC_cap_agg_bwflav2_norm_log', 'SC_dist_agg', 'SC_dist_mean_agg', 'SC_dist_mode_agg', 'SC_dist_median_agg', 'SC_dist_var_agg'])

In [25]:
sio.loadmat('C:/Users/dinar/Downloads/SC_and_tracts_masked_norm.mat').keys()

dict_keys(['__header__', '__version__', '__globals__', 'SC_berlin_masked_norm', 'T_berlin_masked'])

In [29]:
analysis = sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat', squeeze_me=True)


In [40]:
import os

for i in range(50):
    if not os.path.exists(str(i)):
        os.mkdir(str(i))
    pd.DataFrame(analysis['all_empFC'][i]).to_csv(os.path.join(str(i), 'emp_fc.txt'), header=None, index=None, sep='\t')

In [41]:
for i in range(50):
    pd.DataFrame(analysis['all_simFC'][i]).to_csv(os.path.join(str(i), 'sim_fc.txt'), header=None, index=None, sep='\t')

ValueError: Must pass 2-d input. shape=(5, 21, 68, 68)

In [54]:
analysis['all_simFC'][0][0][0].shape

(68, 68)

INFO:bokeh.server.views.ws:WebSocket connection closed: code=1001, reason=None


In [45]:
sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat')['sim_empFC'][0]

array([[[0.23804239, 0.16929712],
        [0.24279337, 0.16359647],
        [0.2489827 , 0.15637819],
        [0.25721996, 0.1471606 ],
        [0.26966658, 0.13497704],
        [0.29621545, 0.11526338],
        [0.35425876, 0.07879483],
        [0.42798619, 0.04709965],
        [0.44917286, 0.05945708],
        [0.43615064, 0.0481446 ],
        [0.3788393 , 0.06297675],
        [0.35778697, 0.06386896],
        [0.24228028, 0.15422429],
        [0.23959489, 0.15788873],
        [0.23799374, 0.16047987],
        [0.23734933, 0.16234749],
        [0.23728761, 0.16373613],
        [0.23797829, 0.16461986],
        [0.23868376, 0.16533423],
        [0.23907762, 0.16590123],
        [0.23924791, 0.16624886]],

       [[0.23796871, 0.16931926],
        [0.24271531, 0.16359723],
        [0.24892268, 0.15636229],
        [0.25788718, 0.14708309],
        [0.27037094, 0.13491108],
        [0.29889317, 0.11489992],
        [0.3366719 , 0.08414685],
        [0.39687966, 0.05584774],
        [0.4

In [42]:
analysis['all_simFC'][i]

array([[[[ 1.        , -0.33046327,  0.14925431, ...,  0.09717291,
          -0.10569616,  0.04418625],
         [-0.33046327,  1.        , -0.10069343, ..., -0.10330446,
           0.11033246, -0.10894342],
         [ 0.14925431, -0.10069343,  1.        , ...,  0.06126735,
          -0.02809838,  0.09689284],
         ...,
         [ 0.09717291, -0.10330446,  0.06126735, ...,  1.        ,
          -0.10941038,  0.25847145],
         [-0.10569616,  0.11033246, -0.02809838, ..., -0.10941038,
           1.        , -0.12422181],
         [ 0.04418625, -0.10894342,  0.09689284, ...,  0.25847145,
          -0.12422181,  1.        ]],

        [[ 1.        , -0.32973375,  0.15192478, ...,  0.10107582,
          -0.10071012,  0.04303347],
         [-0.32973375,  1.        , -0.0997393 , ..., -0.10074695,
           0.11430915, -0.10090421],
         [ 0.15192478, -0.0997393 ,  1.        , ...,  0.0723496 ,
          -0.02177718,  0.10637885],
         ...,
         [ 0.10107582, -0.10074695

In [19]:
sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat').keys()

dict_keys(['__header__', '__version__', '__globals__', 'all_empFC', 'all_simFC', 'sim_empFC', 'avg_bimod', 'avg_freq', 'reg_bimod', 'reg_freq'])

In [43]:
sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat')['all_empFC'].shape

(50, 68, 68)

In [20]:
sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat')['all_simFC'].shape

(50, 5, 21, 68, 68)

In [44]:
sio.loadmat('C:/Users/dinar/Downloads/Analysis_s1.mat')['sim_empFC'].shape

(50, 5, 21, 2)

In [22]:
sio.loadmat('C:/Users/dinar/Desktop/matlab_data_files_SC_and_fMRI/AA_20120815_SC.mat')

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Tue Apr  8 07:01:42 2014',
 '__version__': '1.0',
 '__globals__': [],
 'steps2lenght': array(['The steplength used for this tracking was 0.2mm/step. So for instance, a track length of 10 steps means 2mm.'],
       dtype='<U108'),
 'SC_cap_agg_counts': array([[    0,     1,  1526, ...,     0,     4,     2],
        [    1,     0,    58, ...,     0,     0,    24],
        [ 1526,    58,     0, ...,     0,     0,    54],
        ...,
        [    0,     0,     0, ...,     0,     0, 67012],
        [    4,     0,     0, ...,     0,     0,  5641],
        [    2,    24,    54, ..., 67012,  5641,     0]]),
 'SC_cap_agg_bwflav1': array([[   0,    1, 1415, ...,    0,    4,    2],
        [   1,    0,   57, ...,    0,    0,   23],
        [1415,   57,    0, ...,    0,    0,   54],
        ...,
        [   0,    0,    0, ...,    0,    0, 6724],
        [   4,    0,    0, ...,    0,    0, 1797],
        [   2,   23,   54, ..., 67

In [23]:
sio.loadmat('C:/Users/dinar/Desktop/matlab_data_files_SC_and_fMRI/AA_20120815_fMRI_new.mat')

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Sun Mar 23 18:25:10 2014',
 '__version__': '1.0',
 '__globals__': [],
 'ROI_ID_table': array([[ 1.00000000e+00,  0.00000000e+00,  9.82160000e+04, ...,
         -1.25138600e+03,  1.93981875e+04,  2.06495742e+04],
        [ 2.00000000e+00,  2.00000000e+00,  6.32500000e+03, ...,
          4.62146000e+01,  1.60500693e+04,  1.60038545e+04],
        [ 3.00000000e+00,  4.00000000e+00,  2.03000000e+02, ...,
          7.57800390e+03,  1.74871406e+04,  9.90913670e+03],
        ...,
        [ 1.08000000e+02,  2.03300000e+03,  5.70000000e+01, ...,
          0.00000000e+00,  5.41270800e+03,  5.41270800e+03],
        [ 1.09000000e+02,  2.03400000e+03,  2.80000000e+01, ...,
          1.07815723e+04,  1.42260195e+04,  3.44444730e+03],
        [ 1.10000000e+02,  2.03500000e+03,  2.15000000e+02, ...,
          6.78981700e+02,  1.51475752e+04,  1.44685938e+04]]),
 'FC_cc': array([[ 1.        ,  0.54857184, -0.10775857, ...,  0.07022364,


In [7]:
import os
path = 'C:/Users/dinar/Desktop/gsoc_data/brain_tumor/sub-CON01/ses-preop/ROIts.dat'

os.rename(path, path.replace('dat', 'txt'))

FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:/Users/dinar/Desktop/gsoc_data/brain_tumor/sub-CON01/ses-preop/ROIts.dat' -> 'C:/Users/dinar/Desktop/gsoc_txta/brain_tumor/sub-CON01/ses-preop/ROIts.txt'

In [8]:
from pathlib import Path
p = Path(path)
p.rename(p.with_suffix('.txt'))

WindowsPath('C:/Users/dinar/Desktop/gsoc_data/brain_tumor/sub-CON01/ses-preop/ROIts.txt')

In [15]:
import scipy.io as sio
import os
import numpy as np
import pandas as pd

In [11]:
path = 'C:/Users/dinar/Desktop/test2/data'
files = os.listdir(path)

dict1 = {}
dict1

{}

In [21]:
for file in files:
    if file.endswith('py') or file.endswith('info.txt'): continue
    basename = os.path.basename(file).split('.')[0]
    
    if basename in ['bold_times', 'times']:
        f = pd.read_csv(os.path.join(path, file), index_col=None, header=None, sep='\t')
    else:
        f = pd.read_csv(os.path.join(path, file), index_col=None, header=None, sep='\s')
        
    dict1[basename] = f.to_numpy()

In [23]:
sio.savemat('mat_test.mat', dict1)

In [55]:
file = sio.loadmat('mat_test.mat')
file

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Mon Sep 19 14:46:38 2022',
 '__version__': '1.0',
 '__globals__': [],
 'bold_times': array([[ 100.],
        [ 200.],
        [ 300.],
        [ 400.],
        [ 500.],
        [ 600.],
        [ 700.],
        [ 800.],
        [ 900.],
        [1000.]]),
 'centres': array([[array(['rA1'], dtype='<U3'), array([[-9.885591]]),
         array([[-47.084818]]), array([[-3.13936]])],
        [array(['rA2'], dtype='<U3'), array([[-2.605247]]),
         array([[-55.324507]]), array([[-7.065423]])],
        [array(['rAMYG'], dtype='<U5'), array([[6.489431]]),
         array([[-11.670519]]), array([[-30.851544]])],
        [array(['rCCA'], dtype='<U4'), array([[48.734149]]),
         array([[-2.004701]]), array([[8.019123]])],
        [array(['rCCP'], dtype='<U4'), array([[-12.1714]]),
         array([[-6.494719]]), array([[25.361539]])],
        [array(['rCCR'], dtype='<U4'), array([[-38.1525]]),
         array([[-13.054752]]), arra

In [56]:
file.keys()

dict_keys(['__header__', '__version__', '__globals__', 'bold_times', 'centres', 'distances', 'fc', 'times', 'ts', 'ts_bold', 'weights'])

INFO:bokeh.server.views.ws:WebSocket connection closed: code=1001, reason=None


In [50]:
import scipy.io as sio
import mat73
from sim2bids.app import app
from sim2bids.generate import subjects


def save_mat(sub, folders, ses=None):
    file = traverse_file(sub['path'])
    root = os.path.dirname(sub['path'])
    
    # extract files
    if file is not None:
        for k in file.keys():
            if subjects.accepted(k):
                # save files separately
                print(file[k])
                pd.DataFrame(file[k]).to_csv(os.path.join(root, k + '.txt'), 
                                                                          index=None, header=None, sep='\t')

def save_mat73(subs, folders, ses):
    return mat73.loadmat(subs['path'])


def traverse_file(path):
    name = os.path.basename(path)
    
    try:
        mat = sio.loadmat(path, squeeze_me=True)
    except NotImplementedError:
        return mat73.loadmat(path)
    except sio.matlab._miobase.MatReadError:
        pn.state.notifications.error(f'File `{name}` is empty! Aborting...')
        return None
    else:
        return mat

In [51]:
save_mat({'name': 'mat', 'path': 'C:/Users/dinar/Desktop/gsoc/app_templates/mat_test.mat'}, [])

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]
[['rA1' -9.885591 -47.084818 -3.13936]
 ['rA2' -2.605247 -55.324507 -7.065423]
 ['rAMYG' 6.489431 -11.670519 -30.851544]
 ['rCCA' 48.734149 -2.004701 8.019123]
 ['rCCP' -12.1714 -6.494719 25.361539]
 ['rCCR' -38.1525 -13.054752 -5.607666]
 ['rCCS' 30.150795 -4.286333 -31.136279]
 ['rFEF' 30.400644 -33.753689 34.832572]
 ['rG' 36.159029 -35.084312 -18.938829]
 ['rHC' -12.502286 -24.875165 -20.872351]
 ['rIA' 23.242996 -42.031295 -22.110624]
 ['rIP' 9.822772 -44.114976 -18.760442]
 ['rM1' 8.003023 -32.833685 38.712349]
 ['rPCI' -22.152851 -56.734891 16.852029]
 ['rPCIP' -51.151034 -35.899675 25.679908]
 ['rPCM' -43.927847 -8.226723 27.584594]
 ['rPCS' -30.092058 -33.534852 43.097159]
 ['rPFCCL' 54.048553 -37.427609 12.535183]
 ['rPFCDL' 59.995574 -14.366518 26.025739]
 ['rPFCDM' 59.612735 -2.407101 -0.844581]
 ['rPFCM' 59.286775 -2.547348 -21.924281]
 ['rPFCORB' 47.987255 -16.887697 -39.699154]
 ['rPFCPOL' 79.213202 -15.623481