In [1]:
import sys
import warnings
import panel as pn

# DO NOT remove this line below, otherwise the app won't be found
sys.path.append('..')
warnings.filterwarnings('ignore')

In [2]:
import sim2bids
from sim2bids.sim2bids import MainArea

pn.extension('tabulator', 'ace', 'jsoneditor', 'ipywidgets', sizing_mode='stretch_width', notifications=True)

NotificationArea(sizing_mode='stretch_width')

In [4]:
path = '../output'
sys.path.append(path)

sim2bids.app.app.SoftwareVersion = 2.6
sim2bids.app.app.SoftwareRepository = 'https://github.com/the-virtual-brain/tvb-root/releases/tag/2.6'
sim2bids.app.app.SoftwareName = 'TVB'

app = MainArea()
pn.serve(app.view())

INFO:bokeh.server.server:Starting Bokeh server version 2.4.3 (running on Tornado 6.1)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)


Launching server at http://localhost:57787


INFO:tornado.access:200 GET / (127.0.0.1) 121.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/jsoneditor/npm/jsoneditor@9.1.9/dist/jsoneditor.min.css (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/notificationarea/npm/notyf@3/notyf.min.css (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/datatabulator/tabulator-tables@4.9.3/dist/css/tabulator_simple.min.css (127.0.0.1) 4.00ms
INFO:tornado.access:200 GET /static/extensions/panel/bundled/notificationarea/ajax/libs/font-awesome/5.15.1/css/all.min.css (127.0.0.1) 1.99ms
INFO:tornado.access:200 GET /static/extensions/panel/css/alerts.css (127.0.0.1) 4.00ms
INFO:tornado.access:200 GET /static/extensions/panel/css/debugger.css (127.0.0.1) 3.00ms
INFO:tornado.access:200 GET /static/extensions/panel/css/dataframe.css (127.0.0.1) 6.02ms
INFO:tornado.access:200 GET /static/extensions/panel/css/json.css (127.0.0.1) 10.00ms
INFO:tornado.access:200 GET /static/extensio

ses not found
all files: ['1\\centres.txt', '1\\fc.txt', '1\\times.txt', '1\\ts.txt']
OrderedDict([('sub-01', {'bold_times.txt': {'name': 'bold_times', 'fname': 'bold_times.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\n', 'path': '1\\bold_times.txt', 'ext': 'txt'}, 'centres.txt': {'name': 'centres', 'fname': 'centres.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\\s', 'path': '1\\centres.txt', 'ext': 'txt'}, 'distances.txt': {'name': 'distances', 'fname': 'distances.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\\s', 'path': '1\\distances.txt', 'ext': 'txt'}, 'fc.txt': {'name': 'fc', 'fname': 'fc.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\\s', 'path': '1\\fc.txt', 'ext': 'txt'}, 'times.txt': {'name': 'times', 'fname': 'times.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\n', 'path': '1\\times.txt', 'ext': 'txt'}, 'ts.txt': {'name': 'ts', 'fname': 'ts.txt', 'sid': 'sub-01', 'desc': 'default', 'sep': '\\s', 'path': '1\\ts.txt', 'ext': 'txt'}, 'ts_bold.txt': {'na

ts_bold.txt
weights.txt


In [15]:
import scipy.io as sio
import os
import numpy as np
import pandas as pd

In [11]:
path = 'C:/Users/dinar/Desktop/test2/data'
files = os.listdir(path)

dict1 = {}
dict1

{}

In [21]:
for file in files:
    if file.endswith('py') or file.endswith('info.txt'): continue
    basename = os.path.basename(file).split('.')[0]
    
    if basename in ['bold_times', 'times']:
        f = pd.read_csv(os.path.join(path, file), index_col=None, header=None, sep='\t')
    else:
        f = pd.read_csv(os.path.join(path, file), index_col=None, header=None, sep='\s')
        
    dict1[basename] = f.to_numpy()

In [23]:
sio.savemat('mat_test.mat', dict1)

In [55]:
file = sio.loadmat('mat_test.mat')
file

{'__header__': b'MATLAB 5.0 MAT-file Platform: nt, Created on: Mon Sep 19 14:46:38 2022',
 '__version__': '1.0',
 '__globals__': [],
 'bold_times': array([[ 100.],
        [ 200.],
        [ 300.],
        [ 400.],
        [ 500.],
        [ 600.],
        [ 700.],
        [ 800.],
        [ 900.],
        [1000.]]),
 'centres': array([[array(['rA1'], dtype='<U3'), array([[-9.885591]]),
         array([[-47.084818]]), array([[-3.13936]])],
        [array(['rA2'], dtype='<U3'), array([[-2.605247]]),
         array([[-55.324507]]), array([[-7.065423]])],
        [array(['rAMYG'], dtype='<U5'), array([[6.489431]]),
         array([[-11.670519]]), array([[-30.851544]])],
        [array(['rCCA'], dtype='<U4'), array([[48.734149]]),
         array([[-2.004701]]), array([[8.019123]])],
        [array(['rCCP'], dtype='<U4'), array([[-12.1714]]),
         array([[-6.494719]]), array([[25.361539]])],
        [array(['rCCR'], dtype='<U4'), array([[-38.1525]]),
         array([[-13.054752]]), arra

In [56]:
file.keys()

dict_keys(['__header__', '__version__', '__globals__', 'bold_times', 'centres', 'distances', 'fc', 'times', 'ts', 'ts_bold', 'weights'])

INFO:bokeh.server.views.ws:WebSocket connection closed: code=1001, reason=None


In [50]:
import scipy.io as sio
import mat73
from sim2bids.app import app
from sim2bids.generate import subjects


def save_mat(sub, folders, ses=None):
    file = traverse_file(sub['path'])
    root = os.path.dirname(sub['path'])
    
    # extract files
    if file is not None:
        for k in file.keys():
            if subjects.accepted(k):
                # save files separately
                print(file[k])
                pd.DataFrame(file[k]).to_csv(os.path.join(root, k + '.txt'), 
                                                                          index=None, header=None, sep='\t')

def save_mat73(subs, folders, ses):
    return mat73.loadmat(subs['path'])


def traverse_file(path):
    name = os.path.basename(path)
    
    try:
        mat = sio.loadmat(path, squeeze_me=True)
    except NotImplementedError:
        return mat73.loadmat(path)
    except sio.matlab._miobase.MatReadError:
        pn.state.notifications.error(f'File `{name}` is empty! Aborting...')
        return None
    else:
        return mat

In [51]:
save_mat({'name': 'mat', 'path': 'C:/Users/dinar/Desktop/gsoc/app_templates/mat_test.mat'}, [])

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]
[['rA1' -9.885591 -47.084818 -3.13936]
 ['rA2' -2.605247 -55.324507 -7.065423]
 ['rAMYG' 6.489431 -11.670519 -30.851544]
 ['rCCA' 48.734149 -2.004701 8.019123]
 ['rCCP' -12.1714 -6.494719 25.361539]
 ['rCCR' -38.1525 -13.054752 -5.607666]
 ['rCCS' 30.150795 -4.286333 -31.136279]
 ['rFEF' 30.400644 -33.753689 34.832572]
 ['rG' 36.159029 -35.084312 -18.938829]
 ['rHC' -12.502286 -24.875165 -20.872351]
 ['rIA' 23.242996 -42.031295 -22.110624]
 ['rIP' 9.822772 -44.114976 -18.760442]
 ['rM1' 8.003023 -32.833685 38.712349]
 ['rPCI' -22.152851 -56.734891 16.852029]
 ['rPCIP' -51.151034 -35.899675 25.679908]
 ['rPCM' -43.927847 -8.226723 27.584594]
 ['rPCS' -30.092058 -33.534852 43.097159]
 ['rPFCCL' 54.048553 -37.427609 12.535183]
 ['rPFCDL' 59.995574 -14.366518 26.025739]
 ['rPFCDM' 59.612735 -2.407101 -0.844581]
 ['rPFCM' 59.286775 -2.547348 -21.924281]
 ['rPFCORB' 47.987255 -16.887697 -39.699154]
 ['rPFCPOL' 79.213202 -15.623481