In [56]:
import sys
import os
sys.path.append('..')
# sys.path.append(os.path.abspath('..'))

from incf.incf import MainArea
import param

import io
import panel as pn
import numpy as np
import pandas as pd

pn.extension('tabulator', 'ace', 'jsoneditor', 'ipywidgets', sizing_mode='stretch_width')

In [57]:
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

In [58]:
path = '../output'
sys.path.append(path)

In [59]:
test = MainArea()
pn.serve(test.view())


Launching server at http://localhost:59007


['ALS_binary', 'ALS_weighted', 'HC_binary', 'HC_weighted', 'coord', 'regionDescriptions']
['subs_data', 'subs_time']


In [65]:
os.listdir('C:\\Users\\dinar\\Desktop\\gsoc\\data\\simulations\\1')

['BurstConfiguration_a29116b38d05429588535667ce4d1eee.h5',
 'datatypes',
 'Generic2dOscillator_4e4d2edc01e2448192baf025336e0d73.h5',
 'HeunDeterministicViewModel_4007260a59a443cfbc076eb4c231c6f5.h5',
 'Linear_f639e3b95c48436dae5ffaa29072963e.h5',
 'SimulatorAdapterModel_994a4afbef39461abf2a4feaf9761ca0.h5',
 'SubSampleViewModel_cd2fe7f44797434b9ae2cc3418a9f091.h5']

In [73]:
import h5py 


data = h5py.File('C:\\Users\\dinar\\Desktop\\gsoc\\data\\simulations\\1\\Linear_f639e3b95c48436dae5ffaa29072963e.h5')
dir(data)

['_MutableMapping__marker',
 '__abstractmethods__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_d',
 '_e',
 '_gcpl_crt_order',
 '_id',
 '_ipython_key_completions_',
 '_lapl',
 '_lcpl',
 '_libver',
 'attrs',
 'build_virtual_dataset',
 'clear',
 'close',
 'copy',
 'create_dataset',
 'create_dataset_like',
 'create_group',
 'create_virtual_dataset',
 'driver',
 'file',
 'filename',
 'flush',
 'get',
 'id',
 'items',
 'key

In [75]:
data.keys()

<KeysViewHDF5 ['a', 'b']>

In [77]:
data['a'][:]

array([0.05])

In [78]:
data = h5py.File('C:\\Users\\dinar\\Desktop\\gsoc\\data\\simulations\\1\\datatypes\\Connectivity_6b28b6c61836452bb52cbd18538a7775.h5')
data.keys()

<KeysViewHDF5 ['areas', 'centres', 'cortical', 'hemispheres', 'orientations', 'region_labels', 'tract_lengths', 'weights']>

In [82]:
list(set(['centres', 'weights', 'tract_lengths']).intersection(set(data.keys())))

['weights', 'tract_lengths', 'centres']

In [95]:
data['region_labels'][:]

array([b'rA1', b'rA2', b'rAMYG', b'rCCA', b'rCCP', b'rCCR', b'rCCS',
       b'rFEF', b'rG', b'rHC', b'rIA', b'rIP', b'rM1', b'rPCI', b'rPCIP',
       b'rPCM', b'rPCS', b'rPFCCL', b'rPFCDL', b'rPFCDM', b'rPFCM',
       b'rPFCORB', b'rPFCPOL', b'rPFCVL', b'rPHC', b'rPMCDL', b'rPMCM',
       b'rPMCVL', b'rS1', b'rS2', b'rTCC', b'rTCI', b'rTCPOL', b'rTCS',
       b'rTCV', b'rV1', b'rV2', b'rCC', b'lA1', b'lA2', b'lAMYG', b'lCCA',
       b'lCCP', b'lCCR', b'lCCS', b'lFEF', b'lG', b'lHC', b'lIA', b'lIP',
       b'lM1', b'lPCI', b'lPCIP', b'lPCM', b'lPCS', b'lPFCCL', b'lPFCDL',
       b'lPFCDM', b'lPFCM', b'lPFCORB', b'lPFCPOL', b'lPFCVL', b'lPHC',
       b'lPMCDL', b'lPMCM', b'lPMCVL', b'lS1', b'lS2', b'lTCC', b'lTCI',
       b'lTCPOL', b'lTCS', b'lTCV', b'lV1', b'lV2', b'lCC'], dtype=object)

Creating folder `../output\sub-P0kvO`
Creating folder `../output\sub-P0kvO\net`
Creating folder `../output\sub-P0kvO\spatial`
Creating folder `../output\sub-P0kvO\ts`


In [97]:
data['weights'][:]

array([[2., 2., 0., ..., 0., 0., 0.],
       [3., 2., 0., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 2., 0.],
       [0., 0., 0., ..., 3., 2., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
data['orientations'][:]

array([[ 5.3269728e-01, -1.9247799e-02,  3.3717203e-01],
       [ 5.0751924e-01,  2.0227396e-01,  6.7650411e-01],
       [-2.4510821e-01,  3.6356979e-01, -4.5806268e-01],
       [ 2.4398002e-01,  4.9760675e-01,  2.5458599e-01],
       [ 2.1034941e-02,  5.7507349e-01,  1.7882945e-01],
       [-1.5890180e-01,  4.6505845e-01, -6.0694827e-01],
       [-1.8329208e-01,  6.8771785e-01, -3.3389402e-01],
       [ 4.9602071e-02, -1.1920253e-02,  4.3598602e-01],
       [ 3.8060332e-01, -5.7946675e-01,  1.1053613e-01],
       [-4.3017453e-01,  2.4109761e-01, -5.8290575e-01],
       [ 2.2783116e-01, -6.5815655e-01, -1.2668979e-01],
       [ 1.0975324e-01, -2.6116203e-01,  3.4911050e-01],
       [ 2.0728843e-02, -1.1450961e-01,  1.9501423e-01],
       [-5.3148569e-02, -2.7866605e-01,  1.1536624e-01],
       [-2.2821270e-01, -1.7023107e-01,  2.2850593e-01],
       [-1.9778958e-01,  3.4532294e-01, -5.8313111e-03],
       [ 7.1064903e-02, -2.1930536e-01,  2.8517831e-01],
       [ 2.3001595e-01, -1.6687

In [60]:
loadmat("C:\\Users\\dinar\\Desktop\\simulated_data\\1\\MSE\\P2_log_SC_long_bold_csf_0.1_K11_0.1_K12_0.1.mat")

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Apr 30 16:48:01 2020',
 '__version__': '1.0',
 '__globals__': [],
 'subs_data': array([[[[  -3.84944715,   -1.96095335,   -2.69455228],
          [  -4.04889455,   -1.98311898,   -2.33277659],
          [  -3.94176721,   -2.05415186,   -2.87601393],
          ...,
          [  -4.29774122,   -1.85233491,   -2.90531064],
          [  -4.49811713,   -1.65955181,   -2.68645867],
          [  -3.88675838,   -2.01378071,   -2.872956  ]],
 
         [[  -3.69193033,   -1.68575999,   -2.23651396],
          [  -3.94768865,   -1.94424875,   -2.54331918],
          [  -3.82984156,   -2.33304909,   -2.40755582],
          ...,
          [  -4.06293296,   -1.47831599,   -2.22740778],
          [  -3.79118515,   -1.82996363,   -2.39362346],
          [  -4.25364555,   -1.90993204,   -2.78710827]]],
 
 
        [[[ -65.38614263,  -30.49315838,  -45.18039752],
          [ -64.89151942,  -30.94269337,  -42.84714715],
          [ -6

In [4]:
import mat73
from scipy.io import loadmat

In [10]:
data = loadmat('C:\\Users\\dinar\\Desktop\\simulated_data\\1\\DBS\\newest_timeseries\\GPi_stim\\tvb_timeseries.mat', 
               squeeze_me=True)
data['dims']

array(['Time          ', 'State Variable', 'Region        ',
       'Neurons       '], dtype='<U14')

In [53]:
def find_mat_array(mat):
    data = []

    for k, v in mat.items():
        if type(v) not in [bytes, str, list]:
            data.append(k)

    return data


find_mat_array(data)

['dims', 'attrs', 'data', 'coords', 'transient']

In [55]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Mar 25 16:23:45 2021',
 '__version__': '1.0',
 '__globals__': [],
 'dims': array(['Time          ', 'State Variable', 'Region        ',
        'Neurons       '], dtype='<U14'),
 'attrs': None,
 'data': array([[[9.24158645e-02, 8.96056728e-02, 4.89930394e-02, ...,
          1.01463449e-01, 1.55864629e-02, 5.87542230e-02],
         [1.71684241e+00, 1.73930070e+00, 1.80429717e+00, ...,
          0.00000000e+00, 2.69357687e-04, 1.10159536e-02],
         [1.31146622e+00, 1.31892330e+00, 1.34228813e+00, ...,
          8.75345250e-01, 4.67516590e-01, 6.83007184e-01],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [3.39237277e-01, 3.34011871e-01, 5.75926660e-01, ...,
          3.22753203e-01, 3.02678035e-01, 3.14682057e-01]],
 
        [[9.15398269e-02, 9.09408421e-02, 4.88707572e-02, ...,
          1.00317053e-01, 1.22318579e-02, 5.47590293

['ALS_binary', 'ALS_weighted', 'HC_binary', 'HC_weighted', 'coord', 'regionDescriptions']


In [54]:
type(data['coords'])

numpy.ndarray

In [11]:
data['attrs']

In [12]:
data['data']

array([[[9.24158645e-02, 8.96056728e-02, 4.89930394e-02, ...,
         1.01463449e-01, 1.55864629e-02, 5.87542230e-02],
        [1.71684241e+00, 1.73930070e+00, 1.80429717e+00, ...,
         0.00000000e+00, 2.69357687e-04, 1.10159536e-02],
        [1.31146622e+00, 1.31892330e+00, 1.34228813e+00, ...,
         8.75345250e-01, 4.67516590e-01, 6.83007184e-01],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [3.39237277e-01, 3.34011871e-01, 5.75926660e-01, ...,
         3.22753203e-01, 3.02678035e-01, 3.14682057e-01]],

       [[9.15398269e-02, 9.09408421e-02, 4.88707572e-02, ...,
         1.00317053e-01, 1.22318579e-02, 5.47590293e-02],
        [1.71147984e+00, 1.73721764e+00, 1.80401869e+00, ...,
         4.86993512e-03, 5.56826672e-04, 6.19613245e-03],
        [1.31028333e+00, 1.31882550e+00, 1.34324129e+00, ...,
         9.04258234e-01, 4.82442158e-01, 6.64427306e-01],
        [0.00000000e+00, 0.00000000e+0

In [18]:
dir(data['coords'])

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [36]:
dir(data['coords'])

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [37]:
data['transient']

500.0

In [38]:
data

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Mar 25 16:23:45 2021',
 '__version__': '1.0',
 '__globals__': [],
 'dims': array(['Time          ', 'State Variable', 'Region        ',
        'Neurons       '], dtype='<U14'),
 'attrs': None,
 'data': array([[[9.24158645e-02, 8.96056728e-02, 4.89930394e-02, ...,
          1.01463449e-01, 1.55864629e-02, 5.87542230e-02],
         [1.71684241e+00, 1.73930070e+00, 1.80429717e+00, ...,
          0.00000000e+00, 2.69357687e-04, 1.10159536e-02],
         [1.31146622e+00, 1.31892330e+00, 1.34228813e+00, ...,
          8.75345250e-01, 4.67516590e-01, 6.83007184e-01],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [3.39237277e-01, 3.34011871e-01, 5.75926660e-01, ...,
          3.22753203e-01, 3.02678035e-01, 3.14682057e-01]],
 
        [[9.15398269e-02, 9.09408421e-02, 4.88707572e-02, ...,
          1.00317053e-01, 1.22318579e-02, 5.47590293

In [46]:
dir(data['coords'])

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [52]:
data['coords'].base[0][0]

array(('State Variable', None, array(['S   ', 'Rint', 'R   ', 'Rin ', 'I   '], dtype='<U4')),
      dtype=[('dims', 'O'), ('attrs', 'O'), ('data', 'O')])